const scoreClass = (score) => score >= 75 ? 'positive' : score < 50 ? 'negative' : '';

export function renderThemeLab({ research, instruments, escapeHtml, number }) {
  const byEvidence = new Map(research.evidence.map((item) => [item.id, item]));
  const byInstrument = new Map(instruments.map((item) => [item.id, item]));
  const settings = research.settings;
  return `<div class="section-head"><div><h2>AI-assisted theme lab</h2><p>Evidence-first research across news, blogs, macro, financial, alternative and catalyst data.</p></div><button class="button primary" data-run-themes>Run synthetic detection</button></div>
    <div class="theme-banner"><div><span class="asset-badge">Research only</span><h2>AI proposes; deterministic controls score</h2><p>Candidate themes retain source evidence, uncertainty, catalysts and invalidation. They cannot create orders or target weights.</p></div><div class="theme-run-meta"><span>AI provider</span><b>Not configured</b><small>${research.lastRun ? `Last synthetic run ${new Date(research.lastRun).toLocaleString()}` : 'No detection run yet'}</small></div></div>
    <div class="layout theme-layout"><div><div class="theme-list">${research.themes.length ? research.themes.map((theme) => {
      const evidence = theme.evidenceIds.map((id) => byEvidence.get(id)).filter(Boolean);
      return `<article class="card theme-card"><div class="theme-score"><strong class="${scoreClass(theme.score)}">${number.format(theme.score)}</strong><span>theme score</span><small>${number.format(theme.confidence * 100)}% confidence</small></div><div class="theme-body"><div class="card-head"><div><div class="theme-tags"><span class="asset-badge">${escapeHtml(theme.direction)}</span><span class="asset-badge">${escapeHtml(theme.horizon)}</span><span class="asset-badge">${escapeHtml(theme.generatedBy)}</span></div><h2>${escapeHtml(theme.name)}</h2><p>${escapeHtml(theme.thesis)}</p></div></div><div class="theme-columns"><div><h3>Evidence</h3>${evidence.map((item) => `<button class="evidence-link" data-evidence="${item.id}"><b>${escapeHtml(item.title)}</b><span>${escapeHtml(item.type)} · ${escapeHtml(item.source)} · ${new Date(item.publishedAt).toLocaleDateString()}</span></button>`).join('')}</div><div><h3>Trade expressions</h3>${theme.expressions.map((item) => { const instrument=byInstrument.get(item.instrumentId); return `<div class="expression"><span class="status-badge ${item.stance==='Long'?'pass':item.stance==='Short'?'fail':'review'}">${escapeHtml(item.stance)}</span><div><b>${escapeHtml(instrument?.symbol || item.instrumentId)} · fit ${number.format(item.fit * 100)}</b><small>${escapeHtml(item.rationale)}</small></div></div>`; }).join('') || '<p>No mapped expression.</p>'}</div></div><details><summary>Catalysts and invalidation</summary><div class="theme-columns"><div><h3>Catalysts</h3><ul>${theme.catalysts.map((item) => `<li>${escapeHtml(item)}</li>`).join('')}</ul></div><div><h3>Invalidation</h3><ul>${theme.invalidation.map((item) => `<li>${escapeHtml(item)}</li>`).join('')}</ul></div></div></details></div></article>`;
    }).join('') : '<article class="card empty">Run the bounded synthetic detector to populate research themes.</article>'}</div></div>
    <aside class="card theme-settings"><div class="card-head"><div><h2>Scoring policy</h2><p>Editable, deterministic assumptions.</p></div></div><form id="theme-settings-form"><label>Evidence half-life (days)<input name="halfLifeDays" type="number" min="1" max="365" step="1" value="${settings.halfLifeDays}"></label><label>Minimum independent sources<input name="minimumSources" type="number" min="1" max="20" step="1" value="${settings.minimumSources}"></label>${Object.entries(settings.weights).map(([key,value]) => `<label>${escapeHtml(key)} weight<input name="weight-${key}" type="number" min="0" max="1" step="0.05" value="${value}"></label>`).join('')}<button class="button ghost" type="submit">Save scoring policy</button><p class="safety-note">Weights must sum to 1. Re-run detection after changing them.</p></form><div class="source-mix"><h3>Evidence inventory</h3>${Object.entries(Object.groupBy(research.evidence, (item) => item.type)).map(([type,items]) => `<div><span>${escapeHtml(type)}</span><b>${items.length}</b></div>`).join('')}</div></aside></div>`;
}

export function renderEvidenceDetail(item, escapeHtml, number) {
  if (!item) return '';
  return `<div class="evidence-detail"><div class="theme-tags"><span class="asset-badge">${escapeHtml(item.type)}</span><span class="asset-badge">Reliability ${number.format(item.reliability * 100)}</span><span class="asset-badge">Novelty ${number.format(item.novelty * 100)}</span></div><h3>${escapeHtml(item.title)}</h3><p>${escapeHtml(item.summary)}</p><dl><dt>Source</dt><dd>${escapeHtml(item.source)}</dd><dt>Published</dt><dd>${new Date(item.publishedAt).toLocaleString()}</dd><dt>Data timestamp</dt><dd>${new Date(item.dataTimestamp).toLocaleString()}</dd><dt>Entities</dt><dd>${item.entities.map(escapeHtml).join(', ')}</dd></dl><p class="safety-note">Synthetic evidence. A production record must retain licensed source, URL, retrieval time, content hash and entitlement metadata.</p></div>`;
}
