"""Portable report reads the exact same result as the dashboard."""
from html import escape as esc
from .validation import canonical

def money(v):return 'Unavailable' if v is None else f'{v:,.2f}'
def listing(items):return '<ul>'+''.join('<li>'+esc(str(i))+'</li>' for i in items)+'</ul>' if items else '<p class="muted">None recorded.</p>'
def render_html(result,generated_at=None,title='MacroTrading — Research & Portfolio Review'):
    generated_at=generated_at or result.get('as_of','unspecified');themes=result['themes'];cards=[]
    for key,t in themes.items():
        events=t.get('evidence',t.get('new_evidence',[]));sources=[]
        for event in events:
            links=' · '.join(f'<a href="{esc(s["url"],quote=True)}" target="_blank" rel="noopener noreferrer">{esc(s["title"])}</a>' for s in event['sources'])
            sources.append(f'<div class="evidence"><b>{esc(event["kind"].replace("_"," "))} · {esc(event["direction"])}</b><p>{esc(event["summary"])}</p><small>First known {esc(event.get("first_known_at") or event["observed_at"])} · {links}</small></div>')
        components=' · '.join(f'{k} {v:g}' for k,v in (t.get('components') or {}).items())
        cards.append(f'''<article class="theme-card"><div class="row"><div><small>{esc(t['status'])} · Evidence {esc(t.get('coverage','unverified'))}</small><h2>{esc(t['title'])}</h2></div><b class="score">{'N/A' if t['score'] is None else f"{t['score']:g}"}</b></div><p>{esc(t['hypothesis'])}</p><p class="muted">WATCH: {esc(components)} · Evidence quality: {t.get('evidence_quality') if t.get('evidence_quality') is not None else 'unavailable'} / 100 (not probability)</p><p class="gate">Lifecycle: <b>{esc(t.get('lifecycle','watch'))}</b> — {esc(t.get('lifecycle_reason') or 'No recorded invalidation. Research review does not activate a position.')}</p><p>Market coverage: <b>{esc(t['market'].get('coverage','unverified'))}</b> · Latest eligible session: {esc(t['market'].get('latest_session') or 'none')} · Relative move: {money(t['market']['relative_from_anchor_pct']) + ('%' if t['market']['relative_from_anchor_pct'] is not None else '')}</p><details open><summary>Accepted evidence and contradictions ({len(events)})</summary>{''.join(sources) or '<p>No accepted evidence. The score is a baseline assumption.</p>'}</details><div class="grid"><div><h3>Counterdrivers</h3>{listing(t['counterdrivers'])}<h3>Fundamental tests</h3>{listing(t['fundamental_tests'])}</div><div><h3>Catalysts</h3>{listing(t['catalysts'])}<h3>Invalidation</h3><p>{esc(t['invalidation'])}</p></div></div><h3>Expression</h3><p>{esc(t['expression'].get('proxy','Unspecified'))}: {esc(t['expression'].get('limits',''))}</p><h3>Portfolio decisions required</h3>{listing(t['decisions'])}<details><summary>Paper/implementation risks</summary>{listing(t['paper_risks'])}</details></article>''')
    a=result.get('portfolio');portfolio=''
    if a:
        rows=''.join(f'<tr><td>{esc(r["symbol"])}</td><td>{r["quantity"]:g}</td><td>{money(r["market_value"])}</td><td>{money(r["delta_exposure"])}</td><td>{money(r["unrealized_pnl"])}</td></tr>' for r in a['rows'])
        portfolio=f'<section><h2>Portfolio snapshot · {esc(a["base_currency"])}</h2><p>{"Synthetic demo portfolio" if a.get("demo") else "Imported paper portfolio"} · NAV {money(a["nav"])} · Gross delta {money(a["gross"])} · DV01 {money(a["dv01"])}</p>{listing(a["issues"])}<div class="scroll"><table><tr><th>Instrument</th><th>Quantity</th><th>Market value</th><th>Delta exposure</th><th>Unrealized P&amp;L</th></tr>{rows}</table></div><h3>Scenario approximations</h3>{listing([s["name"]+": "+money(s["pnl"]) for s in result.get("scenarios",[])])}</section>'
    manifest=esc(canonical(result.get('manifest',{})))
    alerts=listing([a['type'].replace('_',' ')+' — '+themes[a['theme_id']]['title'] for a in result['alerts']])
    return f'''<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>{esc(title)}</title><style>body{{margin:0;background:#eff3f8;color:#14263b;font:16px/1.55 system-ui,sans-serif}}main{{max-width:1100px;margin:auto;padding:28px 20px}}header{{background:#142a43;color:white;padding:32px;border-radius:18px}}h1{{font-size:34px;line-height:1.15}}h2{{font-size:23px}}h3{{font-size:15px}}section,.theme-card{{background:white;border:1px solid #dce4ed;border-radius:14px;padding:24px;margin:20px 0}}.row{{display:flex;justify-content:space-between;gap:20px;align-items:center}}.score{{font-size:33px;color:#087b80}}.grid{{display:grid;grid-template-columns:1fr 1fr;gap:24px}}.muted,small{{color:#53687d}}header small{{color:#c4e0ef}}.evidence{{padding:13px 16px;border-left:3px solid #368d92;background:#f4f8fb;margin:12px 0}}.gate{{padding:15px;background:#fff4df;border-left:4px solid #c1842a}}a{{color:#245e99;overflow-wrap:anywhere}}table{{width:100%;border-collapse:collapse;min-width:570px}}td,th{{padding:11px;text-align:left;border-bottom:1px solid #dce4ed}}.scroll{{overflow:auto}}pre{{font-size:12px;white-space:pre-wrap;overflow-wrap:anywhere}}summary{{cursor:pointer;font-weight:700}}@media(max-width:650px){{.grid{{grid-template-columns:1fr}}main{{padding:12px}}header,.theme-card,section{{padding:20px}}}}@media print{{body{{background:white}}header{{print-color-adjust:exact}}}}</style></head><body><main><header><small>MacroTrading v0.5 · {esc(generated_at)}</small><h1>{esc(title)}</h1><p>One accepted research snapshot, its changes, evidence coverage and portfolio context. Paper only.</p></header><section><h2>Changes in this run</h2>{alerts}<p class="gate">{esc(result.get('input_note',''))}</p><p class="gate">Portfolio activation remains a separate reviewed decision. A research score never creates an order. Missing and stale observations remain visible.</p></section>{portfolio}{''.join(cards)}<section><h2>Reproduction manifest</h2><pre>{manifest}</pre><p>WATCH is a prioritisation rubric, not an expected return or probability. Scenario values are approximations using supplied marks, sensitivities and FX rates.</p></section></main></body></html>'''
